pfapp {
    # PATH / IDENTITY
    path = "/usr/local/jails/containers/pathfinder-app";
    host.hostname = "pathfinder-app";

    # STARTUP / LOGGING
    exec.clean;
    exec.consolelog = "/var/log/jails/${name}.console.log";
    exec.start = "/sbin/ifconfig epair10b inet 10.77.0.10/24 up";
    exec.start += "/sbin/route add default 10.77.0.1";
    exec.start += "/bin/sh /etc/rc";
    exec.stop = "/bin/sh /etc/rc.shutdown";

    # DEVICES
    mount.devfs;
    devfs_ruleset = 4;

    # VNET
    vnet;
    vnet.interface = "epair10b";

    exec.prestart = "/sbin/ifconfig epair10 create up";
    exec.prestart += "/sbin/ifconfig bridge77 addm epair10a up";

    exec.poststop = "/sbin/ifconfig epair10a destroy";

    persist;
}

pfdb {
    # PATH / IDENTITY
    path = "/usr/local/jails/containers/pathfinder-db";
    host.hostname = "pathfinder-db";

    # STARTUP / LOGGING
    exec.clean;
    exec.consolelog = "/var/log/jails/${name}.console.log";
    exec.start = "/sbin/ifconfig epair20b inet 10.77.0.20/24 up";
    exec.start += "/sbin/route add default 10.77.0.1";
    exec.start += "/bin/sh /etc/rc";
    exec.stop = "/bin/sh /etc/rc.shutdown";

    # DEVICES
    mount.devfs;
    devfs_ruleset = 4;

    # PRIVATE SYSTEM V IPC FOR POSTGRESQL
    sysvmsg = new;
    sysvsem = new;
    sysvshm = new;

    # VNET
    vnet;
    vnet.interface = "epair20b";

    exec.prestart = "/sbin/ifconfig epair20 create up";
    exec.prestart += "/sbin/ifconfig bridge77 addm epair20a up";

    exec.poststop = "/sbin/ifconfig epair20a destroy";

    persist;
}
